#!/bin/sh
#
# Start the ODCSSS RFID reader daemon
#

start() {
	/root/rfid.sh start
}	
stop() {
	echo -n "Stopping..."
	/root/rfid.sh stop
}
restart() {
	stop
	start
}	

case "$1" in
  start)
  	start
	;;
  stop)
  	stop
	;;
  restart)
  	restart
	;;
  *)
	echo $"Usage: $0 {start|stop|restart}"
	exit 1
esac

exit $?

