#!/bin/sh
#
# Start the network....
#

start() {
	echo "Starting network..."
	/sbin/ifup -a
	#while [ ! `ifconfig | grep 192.168.1.115` ]
	#do
	#	/sbin/ifup mwlan0
	#	/bin/sleep 5
	#done
}	
stop() {
	echo -n "Stopping network..."
	/sbin/ifdown -a
}
restart() {
	stop
	start
}	

case "$1" in
  start)
  	start
	;;
  stop)
  	stop
	;;
  restart|reload)
  	restart
	;;
  *)
	echo $"Usage: $0 {start|stop|restart}"
	exit 1
esac

exit $?

